# Generated by Django 6.0.4 on 2026-04-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usda_nass_api_key', models.CharField(blank=True, help_text='Get a free key at https://quickstats.nass.usda.gov/api/', max_length=200, verbose_name='USDA NASS API Key')),
                ('weather_enabled', models.BooleanField(default=True, help_text='Fetch weather data from Open-Meteo (free, no key required)', verbose_name='Weather sync')),
                ('soil_enabled', models.BooleanField(default=True, help_text='Fetch soil data from SoilGrids (free, no key required)', verbose_name='Soil data sync')),
                ('crop_prices_enabled', models.BooleanField(default=False, help_text='Fetch crop prices from USDA NASS (requires API key above)', verbose_name='Crop price sync')),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.farm')),
            ],
            options={
                'verbose_name_plural': 'farm settings',
                'db_table': 'farm_settings',
            },
        ),
    ]
