# Generated by Django 6.0.4 on 2026-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_farm_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='visible_tickers',
            field=models.JSONField(blank=True, default=list, help_text='Leave empty to show all. Select only the markets relevant to your farm.', verbose_name='Visible commodity prices'),
        ),
    ]
