# Generated by Django 5.2 on 2026-04-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('ear_tag', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('horse', 'Horse'), ('chicken', 'Chicken'), ('duck', 'Duck'), ('turkey', 'Turkey'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('repro_status', models.CharField(choices=[('intact', 'Intact'), ('castrated', 'Castrated'), ('spayed', 'Spayed'), ('pregnant', 'Pregnant'), ('nursing', 'Nursing')], default='intact', max_length=20, verbose_name='Reproductive status')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='livestock/photos/')),
                ('current_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='land.field')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='livestock.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_sire', to='livestock.animal')),
            ],
            options={
                'db_table': 'animal',
                'ordering': ['ear_tag'],
                'unique_together': {('farm', 'ear_tag')},
            },
        ),
        migrations.CreateModel(
            name='FieldMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='livestock.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('from_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='land.field')),
                ('to_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='land.field')),
            ],
            options={
                'db_table': 'field_movement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('record_type', models.CharField(choices=[('immunization', 'Immunization'), ('exam', 'Examination'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('pregnancy_check', 'Pregnancy Check'), ('deworming', 'Deworming'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='livestock/vet_attachments/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='livestock.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'vet_record',
                'ordering': ['-date'],
            },
        ),
    ]
