# Generated by Django 6.0.4 on 2026-04-14 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('hay', 'Hay'), ('grain', 'Grain'), ('silage', 'Silage'), ('pellet', 'Pellet / Concentrate'), ('supplement', 'Supplement / Mineral'), ('fresh_forage', 'Fresh Forage'), ('other', 'Other')], max_length=20)),
                ('default_unit', models.CharField(default='lbs', max_length=20)),
            ],
            options={
                'db_table': 'feed_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(help_text='Specific product or batch name', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='lbs', max_length=20)),
                ('restock_source', models.CharField(choices=[('purchased', 'Purchased'), ('farm_hay', 'Farm Hay'), ('farm_grain', 'Farm Grain'), ('farm_silage', 'Farm Silage'), ('pasture_forage', 'Pasture / Forage'), ('other', 'Other')], default='purchased', help_text='How this feed is restocked when low', max_length=20)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Alert when quantity drops below this level', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='livestock.feedtype')),
            ],
            options={
                'db_table': 'feed_stock',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='lbs', max_length=20)),
                ('date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='livestock.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('feed_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='livestock.feedstock')),
            ],
            options={
                'db_table': 'feeding_log',
                'ordering': ['-date'],
            },
        ),
    ]
