# Generated by Django 6.0.4 on 2026-04-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Feed, Seed, Chemical, Fuel, Medical', max_length=50)),
                ('default_unit', models.CharField(default='units', max_length=20)),
            ],
            options={
                'db_table': 'consumable_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(help_text='Specific product name', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Alert when quantity drops below this level', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('consumable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='consumables.consumabletype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('use', 'Use'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('waste', 'Waste')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for removals', max_digits=10)),
                ('date', models.DateTimeField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text='Invoice number, PO, etc.', max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='consumables.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_transaction',
                'ordering': ['-date'],
            },
        ),
    ]
