# Generated by Django 6.0.4 on 2026-04-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('land', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('farm_animal', 'Farm Animal'), ('farm_crop', 'Farm Crop'), ('purchased', 'Purchased'), ('donated', 'Donated')], default='purchased', max_length=20)),
                ('storage_type', models.CharField(choices=[('fresh', 'Fresh'), ('frozen', 'Frozen'), ('canned', 'Canned'), ('dried', 'Dried'), ('preserved', 'Preserved')], default='fresh', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='lbs', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('source_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produce_items', to='livestock.animal')),
                ('source_crop_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produce_items', to='land.croprecord')),
            ],
            options={
                'db_table': 'food_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProduceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('harvest', 'Harvest'), ('butcher', 'Butcher'), ('purchase', 'Purchase'), ('consume', 'Consume'), ('sell', 'Sell'), ('donate', 'Donate'), ('waste', 'Waste')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive to add, negative to remove', max_digits=10)),
                ('date', models.DateTimeField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='produce.produceitem')),
            ],
            options={
                'db_table': 'food_transaction',
                'ordering': ['-date'],
            },
        ),
    ]
