# Generated by Django 5.2 on 2026-04-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('retired', 'Retired'), ('sold', 'Sold')], default='active', max_length=20)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, help_text='Current hour meter reading', max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='equipment/photos/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('filter', 'Filter Replacement'), ('tires', 'Tires'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('winterization', 'Winterization'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('hours_at_service', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'maintenance_record',
                'ordering': ['-date'],
            },
        ),
    ]
