# Generated by Django 5.2 on 2026-04-09 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('acreage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('centroid_lat', models.FloatField(default=0, editable=False)),
                ('centroid_lon', models.FloatField(default=0, editable=False)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#22c55e', help_text='Hex color for map display', max_length=7)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'field',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(help_text='e.g. 2026-Spring', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('seeded', 'Seeded'), ('growing', 'Growing'), ('fertilized', 'Fertilized'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_unit', models.CharField(blank=True, default='bushels', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_records', to='land.field')),
            ],
            options={
                'db_table': 'crop_record',
                'ordering': ['-season', 'crop_name'],
            },
        ),
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('soilgrids', 'SoilGrids API'), ('usda', 'USDA Soil Data')], default='manual', max_length=20)),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('depth_cm', models.IntegerField(default=30, help_text='Sample depth in cm')),
                ('ph', models.FloatField(blank=True, null=True)),
                ('organic_carbon_pct', models.FloatField(blank=True, null=True, verbose_name='Organic carbon %')),
                ('nitrogen_ppm', models.FloatField(blank=True, null=True, verbose_name='Nitrogen (ppm)')),
                ('sand_pct', models.FloatField(blank=True, null=True)),
                ('silt_pct', models.FloatField(blank=True, null=True)),
                ('clay_pct', models.FloatField(blank=True, null=True)),
                ('texture_class', models.CharField(blank=True, max_length=50)),
                ('cec', models.FloatField(blank=True, null=True, verbose_name='CEC (cmol/kg)')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='land.field')),
            ],
            options={
                'db_table': 'soil_sample',
                'ordering': ['-sample_date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('wind_speed_max_kmh', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='land.field')),
            ],
            options={
                'db_table': 'weather_cache',
                'ordering': ['-date'],
                'unique_together': {('field', 'date')},
            },
        ),
    ]
