# Generated by Django 6.0.4 on 2026-05-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone, auto-populated from Open-Meteo', max_length=50),
        ),
    ]
