# Generated by Django 6.1.1 on 2026-09-30 23:06

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmsettings_visible_tickers'),
        ('land', '0002_add_timezone_to_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('acreage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('parcel_number', models.CharField(blank=True, help_text='County tax parcel ID / APN, if known', max_length=100)),
                ('color', models.CharField(default='#f59e0b', help_text='Hex colour for the property line on the map', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour like #f59e0b.')])),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'parcel',
                'ordering': ['name'],
            },
        ),
    ]
