# Generated by Django 6.0.4 on 2026-04-10 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('building_type', models.CharField(choices=[('barn', 'Barn'), ('shed', 'Shed'), ('silo', 'Silo'), ('garage', 'Garage'), ('greenhouse', 'Greenhouse'), ('coop', 'Coop'), ('stable', 'Stable'), ('shop', 'Shop'), ('house', 'House'), ('other', 'Other')], default='other', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('insurance_policy', models.CharField(blank=True, max_length=100)),
                ('insurance_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Annual insurance cost')),
                ('tax_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Annual property tax')),
                ('photo', models.ImageField(blank=True, upload_to='buildings/photos/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_type', models.CharField(choices=[('roof', 'Roof'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('structural', 'Structural'), ('painting', 'Painting'), ('hvac', 'HVAC'), ('pest_control', 'Pest Control'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='buildings.building')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
            ],
            options={
                'db_table': 'building_maintenance_record',
                'ordering': ['-date'],
            },
        ),
    ]
