# Generated by Django 5.2 on 2026-04-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usda_code', models.CharField(blank=True, help_text='USDA NASS commodity code', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. Grain, Oilseed, Vegetable', max_length=50)),
                ('default_unit', models.CharField(default='bushels', max_length=20)),
            ],
            options={
                'db_table': 'crop_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('yield_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_unit', models.CharField(default='bushels', max_length=20)),
                ('moisture_pct', models.FloatField(blank=True, null=True, verbose_name='Moisture %')),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='land.field')),
            ],
            options={
                'db_table': 'harvest_record',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('state', models.CharField(blank=True, help_text="US state or 'US' for national", max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='$/bushel', max_length=20)),
                ('source', models.CharField(default='USDA NASS', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crops.croptype')),
            ],
            options={
                'db_table': 'market_price',
                'ordering': ['-year'],
                'unique_together': {('crop_type', 'year', 'state')},
            },
        ),
    ]
