# Generated by Django 6.0.4 on 2026-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_seed_crop_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('commodity', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commodity_price',
                'ordering': ['commodity'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
